### ISSUE TITLE
아주 좋은 프로젝트입니다

### ISSUE THREAD

**Issue by mimicode** [hwangseonu/gin-restful#1]
당신이 중국어로 글을 쓸것을 건의합니다, 저는 정말 이해가 안가요, 번역할 수 밖에 없어요 (이 말을 포함하여, 한국어로 번역합니다)

**Comment by hwangseonu** [comment]
Thank you for your interest in this project.
Unfortunately, I can not offer Chinese documents because I do not speak Chinese well. I will try to write English document as soon as possible.

**Comment by hwangseonu** [comment]
당신같은 사람을 위해 예제 코드를 작성하고 있습니다. 예제코드는 [https://github.com/hwangseonu/gin-restful-example](https://github.com/hwangseonu/gin-restful-example) 에서 확인할 수 있습니다.

**Comment by hwangseonu** [comment]
I am writing example code for someone like you. You can find example code at [https://github.com/hwangseonu/gin-restful-example](https://github.com/hwangseonu/gin-restful-example)
